spring.application.name=proyecto1C
server.port=33666

spring.datasource.url=jdbc:mysql://localhost:3306/base1c?createDatabaseIfNotExist=true

spring.datasourse.username=root
spring.datasourse.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring,jpa.hibernate.ddl-auto=update
